name: preloved
description: preloved

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  #ai_barcode: ^3.0.0

  #workmanager: ^0.4.0
  image_picker: ^0.8.4+1
  #image_cropper: ^1.4.0
  cached_network_image: ^3.2.0
  photo_view: ^0.12.0
  font_awesome_flutter: ^9.0.0-nullsafety
  shared_preferences: ^2.0.4
  url_launcher: ^6.0.2
  intl: ^0.17.0
  #flutter_absolute_path: ^1.0.6
  #geolocation: ^1.1.2

  date_time_picker: ^2.0.0
  http_parser: ^4.0.0
 

  fluttertoast: ^7.1.1
  logging: ^1.0.1
  http: ^0.13.3
  http_auth: ^1.0.0
  uuid: ^3.0.4
  badges: ^1.2.0
  path_provider: ^2.0.0
  file_picker: ^4.0.1
  share: ^0.6.4
  validators: ^3.0.0
  device_info: ^2.0.1
  flutter_phoenix: ^0.1.0
  dio: ^4.0.6
  after_layout: ^1.0.7+2
  contained_tab_bar_view: ^0.8.0
  #thumbnails: ^1.0.1
  #visibility_detector: ^0.1.5
  visibility_detector: ^0.4.0+2
  custom_radio_grouped_button: ^1.0.6+1
  flutter_inappwebview: ^5.3.2
  #flutter_downloader: ^1.5.2
  #flutter_restart: ^0.0.3



  #downloads_path_provider_28: ^0.1.2

  permission_handler: ^8.1.6

  mqtt_client: ^9.0.0
  math_expressions: ^2.2.3
  flutter_cached_pdfview: ^0.4.0-nullsafety
  #flutter_barcode_scanner: ^2.0.0
  #flutter_barcode_scanner: ^0.1.0
  #fast_qr_reader_view: ^0.1.5

  share_extend: ^2.0.0
  dismissible_page: ^0.7.0

  #barcode_scanner: ^3.2.4
  #qrscan: ^0.3.2
  #scan: ^1.6.0

  qr_flutter: ^4.0.0
  signature: ^5.0.0
  flutter_js: ^0.5.0+5

  flutter_swiper: ^1.1.6
  chips_choice: ^2.0.1
  fijkplayer: ^0.10.1
  nested: ^1.0.0
  provider: ^6.0.0
  flutter_form_builder: ^6.1.0+1
  scroll_to_id: ^1.4.0
  proste_indexed_stack: ^0.2.4
  animations: ^2.0.1
  #device_id: ^0.2.0
  linkfy_text: ^1.1.5
  custom_rich_text: ^0.0.2
  context_holder: ^0.0.5
  any_link_preview: ^2.0.1-rc
  bot_toast: ^4.0.2
  flutter_svg: 0.22.0
  flutter_html: ^2.2.1
  flutter_sound: ^9.2.13
  sliding_up_panel: ^2.0.0+1
  configurable_expansion_tile_null_safety: ^2.0.3
  camera: ^0.8.1+3


  scroll_to_index: ^2.1.0
  #flutter_audio_recorder2: ^0.0.2
  flutter_custom_tabs: ^0.7.0




  just_audio: ^0.8.1
  #audio_service: ^0.18.7



  audio_service: ^0.18.7
  flutter_snake_navigationbar: ^0.6.1


  flutter_advanced_segment: ^3.0.1
    #getwidget: ^3.0.1
    #fluent_ui: ^3.0.0

  toggle_switch: ^2.0.1
  google_sign_in: ^5.1.0
  #flutter_facebook_login: ^3.0.0
  sign_in_with_apple: ^3.0.0


  flutter_background_service: ^0.1.7

  video_compress: ^3.1.0
  chewie: ^1.0.0
  video_player: ^2.2.3
  #inview_notifier_list: ^3.0.0




  loader_overlay: ^1.0.1
  system_settings: ^2.0.0



  flutter_app_badger: ^1.2.0
  connectivity: ^3.0.6
  event_bus: ^2.0.0
  expandable: ^5.0.1
  #smart_select: ^4.3.2


  # awesome_notifications: ^0.6.16
  image_cropper: ^1.5.0
  multi_select_flutter: ^4.1.2


  cloud_firestore: ^2.2.2
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^5.0.0+2
  firebase_database: ^7.2.1
  firebase_core_platform_interface: 4.5.1




  bubble: ^1.2.1
  google_place: ^0.4.7
  place_picker: ^0.9.19
  google_maps_webservice: ^0.0.18
  google_maps_flutter: ^2.0.9
  flutter_polyline_points: ^1.0.0

  location: ^4.4.0
  geolocator: ^9.0.2
  modal_bottom_sheet: 3.0.0-pre
  #flutter_typeahead: ^4.1.1
  google_fonts: ^2.3.0
  need_resume: ^1.0.6
  #linkwell: ^2.0.5
  clipboard: ^0.1.3
  #flutter_linkify: ^5.0.2
  hash_at_links_detector: ^1.0.1
  #detectable_text_field: ^2.0.4
  #geocoding:  ^2.0.5


  dropdown_search: ^2.0.1
  flutter_rating_bar: ^4.0.0
  flutter_custom_clippers: ^2.1.0
  gridded_pageview: ^0.1.0
  multi_image_picker: ^4.8.1
  bluetooth_print: ^4.3.0
  esc_pos_utils: ^1.1.0
  #esc_pos_printer: ^4.1.0
  esc_pos_utils_plus: ^2.0.1+6
  #firebase_core_platform_interface: 4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/
  fonts:
    - family: f1
      fonts:
       - asset: assets/fonts/f1.ttf


